<?php require("public/partials/head.phtml"); ?>
<link rel="stylesheet" href="/public/css/b4c.css">
	<!-- TEMPLATES -->
	<div id="b4c">
        <div class="subtitle">Programa B4C</div>
        <div class="headimagenes">
			<div class="pleft pimg">
				<img src="/public/img/b4c.png" alt="">
			</div>

            <div class="pright pimg">
				<img src="/public/img/b4carq.png" alt="">
			</div>
		</div>
		<div id="smalltext">
			Herramienta de productividad para la industria de TELCOS (telefonía celular).
		</div>
		<div class="programa">
			<div class="pleft">
                <p>
                    <b>Ventajas de B4C</b>
                    <br><br>
                    - Sistema WEB Parametrizable. <br>
                    - Alto desempeño. <br>
                    - Independencia del usuario para realizar cambios. <br>
                    - Alertas para detectar y corregir errores. <br>
                    - Interfaces más fáciles de usar. <br>
                    - Histórico de configuración (Para análisis de datos).
                    <br> <br>

                    <b>Descripción del Producto:</b>
                    <br> <br>
                    1) Módulo de Tasado, Facturación, Interfaces <br>
                    - El layout de los archivos de entrada es definido por el usuario. <br>
                    - La entrada pueden ser tablas de una base de datos. <br>
                    - Prediseñado para interconexión local o LD, aunque las reglas y <br>
                    operadores se configuran de manera dinámica. <br>
                    - Tiene una interfaz web en donde los usuarios de acuerdo a su roll <br>
                    pueden realizar las configuraciones de las reglas de negocio <br>
                    requeridas. No son necesarios nuevos desarrollos. <br>
                    - Proceso de carga de series de forma masiva (archivo de series). <br>
                    - Facturas para cobro y para validación. <br>
                    - Interfaces con Oracle, SAP, Archivos de texto, Web Services <br>
                </p>
            </div>

            <div class="pright">
                <img src="" alt="">
                <p>
                    2) Módulo Conciliación</br>
                    - El layout de los archivos de entrada es definido por el usuario.</br>
                    - Las reglas para conciliar son definidas por el usuario en la
                    interface WEB.</br>
                    - Procesos en segundo plano y monitoreo desde WEB.</br>
                    - Reportes detallados del proceso de conciliación.</br>
                    <br> <br>
                    3) Módulo de Monitoreo, Alertas y Reportes</br>
                    - Cuenta con pantallas predefinidas para el monitoreo de</br>
                    procesos y tendencia de tráfico.</br>
                    - El usuario puede definir sus propios reportes en la interface</br>
                    WEB. <br>
                    - Los reportes pueden ser exportados a excel.</br>
                </p>
            </div>
        </div>

        <div align="center" class="carq imgcont">
			<div class="bigtitle">Arquitectura</div><br>
			<img src="/public/img/carq.jpg" alt="">
        </div>

        <div align="center" class="imgcont">
			<div class="bigtitle">Casos de tráfico</div><br>
			<img src="/public/img/ctrafico.png" alt="">
			<div class="bigtitle">Alta de Series y Conceptos</div><br>
			<img src="/public/img/caltas.jpg" alt="">
			<div class="bigtitle">Módulo de Facturas</div><br>
			<img src="/public/img/cfactura.jpg" alt="">
        </div>
    </div>

	<?php require("public/partials/fbmsgs.phtml"); ?>
	
	<!-- FOOTER -->
	<?php require("public/partials/foot.phtml"); ?>