<?php require("public/partials/head.phtml"); ?>
<link rel="stylesheet" href="/public/css/dev.css">
	<!-- TEMPLATES -->
	<div id="development">
        <div class="subtitle">
            Desarrollo de Software
        </div>
        <div class="content">
            <p>
                <b>Desarrollo de aplicaciones Web</b>
                <br><br>
                - Desarrollo de aplicaciones para diferentes propósitos basadas en Web
                con conexión a diferentes fuentes de datos y sistemas de reporteo de
				acuerdo a las necesidades de la organización.
				<br>
                - Implementación de procesos de control y seguimiento con base en
                los procesos operativos de su empresa.
                <br><br>
                <b>Fábrica de Software:</b>
                <br><br>
                Ofrecemos a nuestros clientes la opción de desarrollar en nuestras instalaciones sus proyectos, ofreciéndoles un precio fijo por la solución completa con
				ahorros en renta de metro2, equipo de cómputo y energía eléctrica, con entregas semanales de avance.
            </p>
            <div class="image">
                <img src="/public/img/dev.png" alt="">
            </div>
        </div>

    </div>

	<?php require("public/partials/fbmsgs.phtml"); ?>
	
	<!-- FOOTER -->
	<?php require("public/partials/foot.phtml"); ?>