<?php require("public/partials/head.phtml"); ?>
<link rel="stylesheet" href="/public/css/outsourcing.css">

<div id="outsourcing">
	<div class="subtitle">Personal Capacitado OutSourcing</div>
	<div class="content">
		<p class="leftp">
			Teambits ofrece la asignación de personal especializado de acuerdo a
			su perfil técnico para la asignación en oficinas del cliente o bajo el
			esquema de Home Office. Este personal puede ser certificado, si así lo
			solicita.
			Ofrecemos el servicio de desarrollo de aplicaciones en fábrica de software para solucionar la necesidad de proyectos fuera de sus oficinas.
			En ambos casos, asignamos personal experto por tiempo determinado.
			Para ello, analizamos los procesos de negocio del cliente, con el fin de
			proporcionar las alternativas y soluciones con el mejor costo beneficio
			<br><br>
			<b>Administración de Proyectos</b> - Nuestros líderes de proyecto cuentan
			con la experiencia y conocimientos necesarios para recomendar las
			mejores soluciones en tiempo y costo.
			<br><br>
			<b>Consultoría Funcional</b> - Consultores que tienen el conocimiento en las
			herramientas más usadas del mercado: Microsoft / Oracle, arquitecturas abiertas.
			Desarrollando software en plataformas UNIX (Sun Solaris, HP-UX, Digital Unix, Tru64, AIX ) y Windows ( 95, 98, NT, 2012, .NET) con lenguajes
			de programación estructurada y de orientación a objetos, como C/C++,
			Pro*C, PLSQL, Shell, Visual Basic 6.0, Java Developer, tecnología .Net,
			tecnología móvil, etc., implementados en sistemas de tipo Batch y On-line.
		</p>
		<p class="rightp">
			<b>Tecnología Web</b> - Les ofrecemos expertos para proyectos relacionados
			con Oracle iAS y Microsoft IIS (ASP.NET) que logran encontrar soluciones que van de acuerdo con las estrategias de negocio y las tendencias del mercado actual (aplicaciones web).
			<br><br>
			<b>Casos de éxito en Outsourcing</b> - Contamos con el reconocimiento de
			Cablevisión, PWC, Grupo Elektra, Banco Azteca, Alsea, por ser provedor de recursos especializados por más de 5 años consecutivos (Oracle
			OBI, ODI, Tableau, .Net, Java).
			<br><br>
			<b>Consultoría</b>
			- Ofrecemos los servicios de consultoría buscando mejorar los procesos
			de las empresas en tiempo, costo y solución. Para ello, nos enfocamos
			en los procesos, en el producto, y en las personas, sugiriendo e implantando soluciones de software/hardware.
		</p>
	</div>
	<img src="/public/img/os.png" alt="">
</div>
<?php require("public/partials/fbmsgs.phtml"); ?>
<?php require("public/partials/foot.phtml"); ?>