<?php require("public/partials/head.phtml"); ?>
	<!-- TEMPLATES -->
	<link rel="stylesheet" href="/public/css/products.css">
    <div class="subtitle">
        Productos
    </div>
	<div class="productList">
		<p align="center">Teambits cuenta con varios productos utilizados ya por empresas mexicanas.</p>
		<br>
		<div class="productOption" align="center">
			<a href="/products/erp" class="productRef">Fusión pro</a> <br> <br>
			<a href="/products/dpl" class="productRef">DPL</a> <br> <br>
			<a href="/products/b4c" class="productRef">B4C</a>
		</div>
	</div>
	<br> <br>
	<!-- FOOTER -->
	<?php require("public/partials/foot.phtml"); ?>