<?php require("public/partials/head.phtml"); ?>
<link rel="stylesheet" href="/public/css/training.css">
    <div id="training">
        <div class="ttitle">
			Capacitación en Tecnologías de la Información 
        </div>
        <p>
            Ofrecemos el mejor grupo de consultores, dedicados a la investigación e implementación de nuevas tecnologías en diversas plataformas, lenguajes,
            herramientas, y base de datos.
            Cursos y planes de capacitación y cursos de preparación para certificación de evaluaciones oficiales, como:
        </p>
        <div class="tcap">
            <div class="content">
                <ul>
                    <li>UNIX (Sun Solaris, HP-UX, Digital, Unix, Tr64, AIX)</li>
                    <li>Windows (95, 98, NT, 2000, XP, Vista, .Net) (se necesita actualizar?)</li>
                    <li>Lenguajes de programación estructurada y orientada a objetos:</li>
                    <li>Java, C/C++, Pro*C. Pl Shell, Visual Basic, Framework .Net, Mobile.</li>
                    <li>SAP, Manejadores de Bases de datos:</li>
                    <li>Oracle, SQL Server, MySQL, PostgreSQL, DB2, Sybase, entre otros.</li>
                </ul>
            </div>
            <div class="image">
                <img src="/public/img/imgtrain.png">
            </div>
        </div>

        <div class="tcur" align="center">
			<div class="subtitle">Brindamos capacitación en: </div>
			<div class="tcurContent">
				<div class="pleft">
					<div class="type">
						<b>Manejadores de base de datos</b>
						<br>
						<br>
						Cursos para el desarrollo de bases de datos, desde creación de tablas hasta tining y creación
						de Triggers, PL, entre otros.
					</div>
					<br>
					<div class="type">
						<b>Seminarios de Planeación</b>
						<ul>
							<li>-Evaluación de Proyectos de Inversión </li>
							<li>-Administración de Proyectos en Telecomunicaciones </li>
							<li>-Re-ingeniería de Procesos en las Telecomunicaciones</li>
						</ul>
				
					</div>
				
					<div class="type">
						<b>Metodología SCRUM de ITIL</b>
						<br><br>
						-Adoptar una estrategia de desarrollo incremental 
						<br>
						-Basar la calidad del resultado más en el conocimiento
						táctico de las personas 
						<br>
						-Solapamiento de las diferentes fases del desarrollo
					</div>
				</div>
					
				<div class="pright">
					<div class="type">
						<b>Cursos personalizados</b>
						<br> <br>
						También contamos con una coleccion de cursos para satisfacer las necesidades tecnológicas de proyectos
						que requieren temas especificos de conocimiento
					</div>
					<br>
					<div class="type">
						<b>Sistemas Ofimáticas y de su uso general</b>
						<br> <br>
						Cursos de capacitación para personal de oficina que busca mejorar el uso de los recursos
						informáticos en su actividad cotidiana
					</div>
					<br>
					<div class="type">
						<b>Lenguajes de desarrollo</b>
						<br> <br>
						Cursos esarrollados bajo estándares de enseñanza probados que facilitan el proceso de aprendizaje y entretenimiento
					</div>
				</div>
			</div>
        </div>
    </div>

	<!-- Comentarios -->
	<div class="division"></div>
	<?php require("public/partials/fbmsgs.phtml"); ?>
	<!-- /Comentarios -->

    <?php require("public/partials/foot.phtml"); ?>