<!-- /Template -->
	<link rel="stylesheet" href="/public/css/footer.css">
	<div class="footer">
		<div class="menus">
			<div class="contact">
				<div class="contactLogo">
					<img src="/public/img/footLogo.png"> <br>
					<p style="font-size: 12px;">
					<a href="/#notasdeinteres" style="padding-right:10px;">Notas de interés</a>
					<a href="/board">Bolsa de trabajo</a></p> <br> 					
					<img src="/public/img/contacto.png" onclick="window.location.href='/#contactanos'">
				</div>
			</div>

			<div class="meetus">
				<div class="footerTitle">Conócenos</div>
				<ul class="urls">
					<li><a href="/about">¿Quienes somos?</a></li>
					<li><a href="/about#alliances">Alianzas</a></li>
					<li><a href="/about#valuesSection">Nuestros valores</a></li>
					<li><a href="/#clients">¿Quienes son nuestros clientes?</a></li>
				</ul>
			</div>

			<div class="services">
				<div class="footerTitle">Servicios</div>
				<ul class="urls">
					<li><a href="/services/outsourcing">Outsourcing</a></li>
					<li><a href="/services/training">Capacitación</a></li>
					<li><a href="/services/development">Desarrollo de software</a></li>
				</ul>
			</div>

			<div class="products">
				<div class="footerTitle">Productos</div>
				<ul class="urls">
					<li><a href="/products/b4c">B4C</a></li>
					<li><a href="/products/dpl">DPL</a></li>
					<li><a href="/products/erp">ERP FusionPro</a></li>
				</ul>
			</div>

			<div class="projects">
				<div class="footerTitle">Proyectos</div>
				<ul class="urls">
					<li><a href="/projects">Proyectos destacados</a></li>
				</ul>
			</div>

			<div class="social">
				<a href="https://www.facebook.com/Teambits/"><img src="/public/img/fb.png" alt=""></a>
				<a href="https://twitter.com/TeambitsIT"><img src="/public/img/twit.png" alt=""></a>
			</div>
		</div>
	</div>
</body>
</html>